config/routes.rb
Rails.application.routes.draw do

  root 'todos#index'

  resources :todos

  get 'todos/:id/move_placement' => 'todos#move_placement', as: :move

end

app/models/todo.rb
class Todo < ActiveRecord::Base

  validates :description, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController

  def index
    @todos = Todo.all.sort_by(&:position)
    @todo = Todo.new
  end

  def create
    @todos = Todo.all
    @todo = Todo.new(todo_params)
    @todo.position = @todos.count + 1
    if @todo.save
      redirect_to root_path
    else
      render :index
    end
  end

  def move_placement
    @todo = Todo.find(params[:id])

    current_placement = @todo.position
    other_placement = current_placement + params[:direction].to_i
    other_todo = Todo.find_by(position: other_placement)

    other_todo.update(position: other_placement - params[:direction].to_i)
    @todo.update(position: other_placement)

    redirect_to root_path
  end

  def update

  end

  def destroy

  end

  private
  def todo_params
    params.require(:todo).permit(:position, :description, :completed)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TodoList</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/todos/index.html.erb
<h1>To Do List</h1>
<br>
<h4>New To Do</h4>

<%= form_for @todo do |f| %>

  <%= f.label :description %>
  <%= f.text_field :description %>
  <%= f.submit %>

<% end %>

<ol>
  <% @todos.each do |task| %>
    <li>
      <%= task.description %>
      <% unless task == @todos.first %>
        <%= link_to 'up', move_path(task, direction: -1) %>
      <% end %>
      <% unless task == @todos.last %>
        <%= link_to 'down', move_path(task, direction: 1) %>
      <% end %>
    </li>
  <% end %>
</ol>